language: node_js
node_js:
- '6'
sudo: false
cache:
  directories:
  - "$HOME/.npm"
  - "$HOME/.cache"
before_install:
- npm config set spin false
- npm install -g bower phantomjs-prebuilt ember-cli
- bower --version
- phantomjs --version
install:
- npm install
- bower install
script:
- ember test
before_deploy:
- ember build --environment=production
deploy:
  skip_cleanup: true
  provider: s3
  access_key_id: AKIAJ5ZO3H5WVLLW7MMA
  secret_access_key:
    secure: L4sW893sDvDHzYd8BzVl3ap6JkAVQHWgm0pIuE6DOTZ1g/nLksxlDhzTpD64HcTS+dSbPSFiUyvNS1QHsV8tqQvGpAGEHZ5MZihXQF4iBWwjcuPBz7vAbxlaS81bHkF3mfdLszgCs4PrshPsLeuRMqr6eba73SxbV0/8fdHRzm7cs/WNO6w1OvosN08CyD9dx71pSgn4AvGmBeGzWlxJ7fcnHIltN6eYUJ51HpJDGUVjyhVKrNZ8JWNNubgEB2Hxl2AGXPTa7nvo8aICApmjA1Rkau3rFPTHRJq7xw7/kUlZXRWA3wVzWb30Ybt+ncg6c4GyGoAjHNMD4CykbOz7CmatfLY4R6EP1mpWYW01xaiEqE/Qmy/jSu9GWno8wxoGoAwDnqbceKYXax537Qn+9uo/tByHNUC7QfPU1k3ctRPi6gSyKkPrnIaoiKry7v1mGpFiJZ9aXvmHRV6S5K6RnBvsaqU4oPRw/QI21C7rO+aDlsFWFAVKhj4CBhABS4Ez597HsdKbrLRSnAkgzvDssuztrOfyJhz2tItGgpf6fFSxmvauIJcS0WR4gdDpt06bmrQEy5WZKxnTC9OKqOLjQ5AsogigJpaHTrBJKDcb4ZI9E38UvAt5v2NSUB2xmUl9wsQQYEvB9f3QbPMHie8GbVorDJcrdneXi6fgTMBmf/4=
  bucket: thewonderbars.com
  local-dir: dist
  acl: public_read
  on:
    repo: waxpoetic/thewonderbars.com
    branch: master
after_deploy:
- aws configure set preview.cloudfront true
- aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID
  --paths "/*"
env:
  global:
    secure: ORINjMi68EaZ1lTlknHpQKAwW9byhzLJGSGqm2dvNSELjoOE+0Cv9lfAXagVMVDno7heNnJ4MXSdh+784yyoSYKFIst9leXAQ6WwrLuqayhqVxIacwQJLWHMjEunL/mUSj2DYZVKJ4TdNSphvGcYa3h2+vjDdHQFK9GRrGPDyhJiudIWU+GsQ3XVX2zGmB9qkK2TQwh6+XkMnsOivLkcrPmVtJ1PujA52RwxQxS/58+WauqU35q4L/WP80IQ511cl5jpOgSTSd8Scx8eH3C9RwJy8wUi3gLxvHkyQL9t55y384Jx3xoKE3bF3+0DsXmNCnPuhzX4xIHMz4RWrq1/pVDLvqs/hpAAeitiZGkJph2PnT7vhsHOn60/MfCN1+lJhIbwJDQKJmkiDbrsNAH4z9CcgWm4MgIYqtqKACr0Kn655UI0XWRYyq3zm+2edsImRWvMiTBcUEjb8y0HlEnihUWUUULYPtgbkoEsmlC9UynZBCe9KPcJNBlBS22dCsdfeUs+ZpjNO2RvIufQJtopZvoJhB2wPqBHAkVgN3g06twJeqyHLjGCFiT/rydg/s6wb5CHAHY4JIVaBIANrhPznEbq+HfyyWTeE9tG0Og7RHXKY3r9OlnZqC+XwH1QRNZYdJwrmnSeHZ5dN5hMo13LIVYsbq2yWHieqtV8drcJ9MY=
